
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSD Hubs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'DesignSystem',:path => '/Internals/iOS/DesignSystem'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Messaging'

end
